export const path = {
  PUBLIC: "/*",
  HOME: "*",
  LOGIN: "login",
  // PRODUCT: ":product",
  INTRODUTE: "introduce",
  PAYMENT: "payment",
  CONTACT: "contact",
  NEW: "new",
  BLOG: "blog",
  REVIEWBLOG: ":id",
  REVIEWPRODUCT: ":title/:pid",
  LAYOUTPD: "product",
  CATEGORYPD: ":category",
};
